name: Checks - spelling

on:
  pull_request:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  spelling_check:
    if: ${{ github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/autofix')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Install python3-pip
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends python3-pip

      - name: Install codespell
        run: pip install codespell

      - name: Print codespell version
        run: codespell --version

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run codespell
        run: |
          ./scripts/spelling.sh

      - name: Run git diff to see if anything changed
        run: /usr/bin/git diff --name-only --exit-code

      - name: Run git diff if we failed
        if: failure()
        run: /usr/bin/git diff > spelling.patch

      - name: Archive diff as a patch if we failed
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: spelling.patch
          path: |
            ${{ github.workspace }}/spelling.patch

  apply_spelling:
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') && (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/autofix')) }}
    needs: spelling_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Checkout correct git ref
        uses: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download the git diff from spelling_check
        uses: actions/download-artifact@v4
        with:
          name: spelling.patch

      - name: Apply patch
        run: |
          git apply spelling.patch
          rm spelling.patch

      - name: Commit fixes
        run: |
          git config user.name "format-robot"
          git config user.email "no-reply@llnl.gov"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am 'apply spelling updates'
            git push
          fi
